version: '3.7'

services:
  app:
    image: ecommerce-fe
    container_name: ecommerce-fe
    env_file: .env.local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
